// GENERATED by tools/generate-fabric-shots.mjs -- do not edit by hand.
//
// One photograph per product and fabric. Together these cover every
// configuration the shop offers, because the dimensions that do not change the
// picture -- window size, operation, hardware colour -- are not multiplied into
// the file set, and colour is applied as a dye in the browser rather than baked.
//
// ENUMERATED, NOT CONSTRUCTED, and that is the point of the file. A path built
// at runtime is invisible to every audit in the repository; see the
// specification's note on why, and what it cost the wardrobe renders to learn.
// Because each entry carries its own `file` string, `npm run check:fabric-shots`
// can assert that all of them are still on disk.
//
// A shot with a `mask` is DYED: the fabric in it has been normalised to white,
// and the card multiplies the chosen colour through the mask. One mask serves
// every fabric of a product -- they are the same window in the same room, so the
// blind occupies the same pixels in all of them.

export interface FabricShot {
  /** Catalogue item id. */
  product: string;
  /** Variant id within that product -- its 'Fabric type' or equivalent. Null
   * where the product has no fabric type and this is its one photograph. */
  fabric: string | null;
  /** File name within /images/fabrics. */
  file: string;
  /** Mask file name, or null where the variant IS the material and there is
   * nothing to dye -- timber is timber-coloured. */
  mask: string | null;
  /** The headrail and bottom bar, cut separately so the hardware colour can
   * paint them. Metal must not take the fabric's dye, and it has a colour card
   * of its own. */
  hardware: string | null;
  /** How fully this fabric takes its dye, 0..1. A blockout is opaque so its
   * colour is the colour; a sheer is mostly air with daylight through it, so
   * the same dye lands pale. Without this, Black blockout and Black sheer
   * render identically and the fabric row appears to do nothing on exactly the
   * colours where it matters most. */
  dye: number;
  /** How much of the swatch's hue and chroma is laid on WITHOUT touching how
   * bright the cloth is, 0..1 -- a CSS color blend rather than a multiply. Only
   * a sheer takes any. Almost everything you see in one is light coming through
   * it, and multiply dims that as hard as it dims the fabric, so a Truffle sheer
   * turns into a murky linen with the garden going out behind it. This carries
   * the colour; dye carries only the value. */
  tint: number;
  /** How much of the photograph's own modelling the card paints back over the
   * dye, 0..1, scaled there by how dark the chosen colour is. Multiplying by a
   * dark colour flattens a cloth as well as darkening it, and this returns the
   * sheen -- a reflection off the surface, which was never the dye's to take.
   * 0 where the cloth was photographed near-white and a soft-light pass would
   * lift more than it restores. */
  sheen: number;
  /** How much of the metal's own highlight is soft-lit back over the painted
   * hardware, 0..1. 0.4 suits a roller's chrome headrail -- a small bright
   * cylinder that lifts a dark swatch badly if given more. An awning's cassette
   * and arms are large matte extrusions and need 0.7, or they render as flat
   * cut-out shapes rather than parts of the machine. */
  spec: number;
  /** WHAT THIS CLOTH PHOTOGRAPHS AS, [r, g, b] — the white the dye is
   * multiplied through, measured under the product's mask.
   *
   * The header above says the fabric has been normalised to white. It has not:
   * these run from 240,235,228 down to 200,191,176, and every one of them is
   * warmer than it is blue. Multiplying a swatch through that puts the cast on
   * the swatch, which is why White rendered as cream. The card divides it out
   * first -- see dyePaint in ShopCard.
   *
   * Absent on an undyed shot, which has nothing to divide out. */
  white?: [number, number, number];
}

export const FABRIC_SHOT_DIR = '/images/fabrics';

export const FABRIC_SHOTS: FabricShot[] = [
  { product: 'curtains', fabric: 'blockout', file: 'curtains-blockout.webp', mask: 'curtains.mask.png', hardware: 'curtains.hardware.png', dye: 1, tint: 0, sheen: 0.5, spec: 0.4, white: [203, 194, 182] },
  { product: 'curtains', fabric: 'sheer', file: 'curtains-sheer.webp', mask: 'curtains.mask.png', hardware: 'curtains.hardware.png', dye: 0.5, tint: 0.9, sheen: 0.5, spec: 0.4, white: [230, 227, 222] },
  { product: 'folding-arm-awnings', fabric: null, file: 'folding-arm-awnings.webp', mask: 'folding-arm-awnings.mask.png', hardware: 'folding-arm-awnings.hardware.png', dye: 1, tint: 0, sheen: 0.7, spec: 0.7, white: [223, 214, 202] },
  { product: 'plantation-shutters', fabric: null, file: 'plantation-shutters.webp', mask: 'plantation-shutters.mask.png', hardware: null, dye: 1, tint: 0, sheen: 0, spec: 0.4, white: [208, 201, 189] },
  { product: 'roller-blinds', fabric: 'blockout', file: 'roller-blinds-blockout.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 1, tint: 0, sheen: 0, spec: 0.4, white: [223, 217, 211] },
  { product: 'roller-blinds', fabric: 'dual', file: 'roller-blinds-dual.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 0.88, tint: 0, sheen: 0, spec: 0.4, white: [200, 191, 176] },
  { product: 'roller-blinds', fabric: 'lightfilter', file: 'roller-blinds-lightfilter.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 0.7, tint: 0, sheen: 0, spec: 0.4, white: [240, 235, 228] },
  { product: 'roller-blinds', fabric: 'sunscreen', file: 'roller-blinds-sunscreen.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 0.55, tint: 0, sheen: 0, spec: 0.4, white: [216, 208, 195] },
  { product: 'venetian-blinds', fabric: null, file: 'venetian-blinds.webp', mask: 'venetian-blinds.mask.png', hardware: null, dye: 1, tint: 0, sheen: 0, spec: 0.4, white: [221, 215, 203] },
];

/** The shot for a configuration, or undefined where none has been photographed
 * yet -- the card falls back to the product's own hero image.
 *
 * THREE STEPS DOWN. The exact fabric first. Then the product's fabric-less
 * photograph, for a product that has no fabric type. Then ANY shot of that
 * product -- because a venetian photographed in aluminium is still a photograph
 * of a venetian, and showing it when someone picks Timber beats falling back to
 * a hero image of a different room. What it costs is that the picture does not
 * follow that one choice; what it buys is that the card keeps its product. */
export const fabricShot = (product: string, fabric: string | undefined): FabricShot | undefined =>
  FABRIC_SHOTS.find(s => s.product === product && s.fabric === fabric)
  ?? FABRIC_SHOTS.find(s => s.product === product && s.fabric === null)
  ?? FABRIC_SHOTS.find(s => s.product === product);
