// GENERATED by tools/generate-fabric-shots.mjs -- do not edit by hand.
//
// One photograph per product and fabric. Together these cover every
// configuration the shop offers, because the dimensions that do not change the
// picture -- window size, operation, hardware colour -- are not multiplied into
// the file set, and colour is applied as a dye in the browser rather than baked.
//
// ENUMERATED, NOT CONSTRUCTED, and that is the point of the file. A path built
// at runtime is invisible to every audit in the repository; see the
// specification's note on why, and what it cost the wardrobe renders to learn.
// Because each entry carries its own `file` string, `npm run check:fabric-shots`
// can assert that all of them are still on disk.
//
// A shot with a `mask` is DYED: the fabric in it has been normalised to white,
// and the card multiplies the chosen colour through the mask. One mask serves
// every fabric of a product -- they are the same window in the same room, so the
// blind occupies the same pixels in all of them.

export interface FabricShot {
  /** Catalogue item id. */
  product: string;
  /** Variant id within that product -- its 'Fabric type' or equivalent. Null
   * where the product has no fabric type and this is its one photograph. */
  fabric: string | null;
  /** File name within /images/fabrics. */
  file: string;
  /** Mask file name, or null where the variant IS the material and there is
   * nothing to dye -- timber is timber-coloured. */
  mask: string | null;
  /** The headrail and bottom bar, cut separately so the hardware colour can
   * paint them. Metal must not take the fabric's dye, and it has a colour card
   * of its own. */
  hardware: string | null;
  /** How fully this fabric takes its dye, 0..1. A blockout is opaque so its
   * colour is the colour; a sheer is mostly air with daylight through it, so
   * the same dye lands pale. Without this, Black blockout and Black sheer
   * render identically and the fabric row appears to do nothing on exactly the
   * colours where it matters most. */
  dye: number;
}

export const FABRIC_SHOT_DIR = '/images/fabrics';

export const FABRIC_SHOTS: FabricShot[] = [
  { product: 'curtains', fabric: 'blockout', file: 'curtains-blockout.webp', mask: 'curtains.mask.png', hardware: null, dye: 1 },
  { product: 'curtains', fabric: 'sheer', file: 'curtains-sheer.webp', mask: 'curtains.mask.png', hardware: null, dye: 0.38 },
  { product: 'folding-arm-awnings', fabric: 'acrylic', file: 'folding-arm-awnings-acrylic.webp', mask: null, hardware: null, dye: 1 },
  { product: 'plantation-shutters', fabric: null, file: 'plantation-shutters.webp', mask: 'plantation-shutters.mask.png', hardware: null, dye: 1 },
  { product: 'roller-blinds', fabric: 'blockout', file: 'roller-blinds-blockout.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 1 },
  { product: 'roller-blinds', fabric: 'dual', file: 'roller-blinds-dual.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 0.88 },
  { product: 'roller-blinds', fabric: 'lightfilter', file: 'roller-blinds-lightfilter.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 0.7 },
  { product: 'roller-blinds', fabric: 'sunscreen', file: 'roller-blinds-sunscreen.webp', mask: 'roller-blinds.mask.png', hardware: 'roller-blinds.hardware.png', dye: 0.55 },
  { product: 'roller-shutters', fabric: 'aluminium', file: 'roller-shutters-aluminium.webp', mask: null, hardware: null, dye: 1 },
  { product: 'venetian-blinds', fabric: null, file: 'venetian-blinds.webp', mask: 'venetian-blinds.mask.png', hardware: null, dye: 1 },
  { product: 'zip-guide-systems', fabric: 'mesh', file: 'zip-guide-systems-mesh.webp', mask: null, hardware: null, dye: 1 },
];

/** The shot for a configuration, or undefined where none has been photographed
 * yet -- the card falls back to the product's own hero image.
 *
 * THREE STEPS DOWN. The exact fabric first. Then the product's fabric-less
 * photograph, for a product that has no fabric type. Then ANY shot of that
 * product -- because a venetian photographed in aluminium is still a photograph
 * of a venetian, and showing it when someone picks Timber beats falling back to
 * a hero image of a different room. What it costs is that the picture does not
 * follow that one choice; what it buys is that the card keeps its product. */
export const fabricShot = (product: string, fabric: string | undefined): FabricShot | undefined =>
  FABRIC_SHOTS.find(s => s.product === product && s.fabric === fabric)
  ?? FABRIC_SHOTS.find(s => s.product === product && s.fabric === null)
  ?? FABRIC_SHOTS.find(s => s.product === product);
