// ---------------------------------------------------------------------------
// POST /api/csp-report
//
// WHAT THIS IS FOR. A Content Security Policy that is never reported on tells
// you nothing. The headers in netlify.toml block an injected script; they do
// not tell anybody that one was injected, so the first evidence of a
// compromised dependency or a stored-XSS attempt would be a customer noticing.
// This is the channel that turns "the policy held" into "the policy held, at
// 04:12, against script from this origin, on this page".
//
// It is deliberately the dumbest endpoint on the site:
//
//   * It writes to the log and nothing else. No database, no email, no
//     outbound call — a reporting endpoint that can be made to do work is a
//     denial-of-service amplifier pointed at your own infrastructure.
//   * It answers 204 to everything, always. Malformed, oversized, rate
//     limited, wrong content type: 204. A report endpoint that distinguishes
//     between cases is an oracle, and there is nothing here worth telling
//     anyone apart.
//   * Every value it logs is sanitised first. See safeField.
//
// NO ORIGIN CHECK, ON PURPOSE. Violation reports are generated by the browser,
// not by our page, and arrive with `Origin: null` or no Origin at all. The
// controls that matter here are the rate limit and the size cap.
// ---------------------------------------------------------------------------

import { readBody } from '../lib/http'
import { checkRateLimit } from '../lib/rateLimit'

import type { Config, Context } from '@netlify/functions'

/** Reports are attacker-influenceable: a violation's `blocked-uri` and
 *  `script-sample` echo back content from the page that triggered it. Anything
 *  written to a log line must therefore be stripped of the characters that let
 *  a value forge a second log entry, and capped so one report cannot bury the
 *  rest of the log. */
function safeField(value: unknown, max = 300): string {
  if (typeof value !== 'string' || value === '') return '-'
  const printable = [...value.slice(0, max)]
    .map(character => (character.codePointAt(0)! < 32 || character.codePointAt(0) === 127 ? ' ' : character))
    .join('')
    .trim()
  return printable === '' ? '-' : printable
}

/** Browsers send two shapes. The legacy `report-uri` delivery posts
 *  `{"csp-report": {...}}` as application/csp-report; the Reporting API posts
 *  an array of `{type, url, body:{...}}` as application/reports+json. Read both
 *  rather than depending on which one a given browser chose. */
function violations(parsed: unknown): Record<string, unknown>[] {
  if (Array.isArray(parsed)) {
    return parsed
      .filter((entry): entry is Record<string, unknown> => !!entry && typeof entry === 'object')
      .filter(entry => entry.type === undefined || entry.type === 'csp-violation')
      .map(entry => (entry.body && typeof entry.body === 'object' ? entry.body as Record<string, unknown> : entry))
  }
  if (parsed && typeof parsed === 'object') {
    const report = (parsed as Record<string, unknown>)['csp-report']
    return [((report && typeof report === 'object' ? report : parsed) as Record<string, unknown>)]
  }
  return []
}

/** One log line from one violation. The two delivery shapes spell every field
 *  differently — camelCase in the Reporting API, hyphenated in the legacy
 *  report — so each value is read under both names. */
function line(report: Record<string, unknown>): string {
  const field = (max: number, ...names: string[]) =>
    safeField(names.map(name => report[name]).find(value => value !== undefined), max)
  return ['[csp]',
    `directive=${field(80, 'effectiveDirective', 'effective-directive', 'violatedDirective', 'violated-directive')}`,
    `blocked=${field(200, 'blockedURL', 'blocked-uri')}`,
    `document=${field(200, 'documentURL', 'document-uri')}`,
    `disposition=${field(20, 'disposition')}`,
    `sample=${field(120, 'sample', 'script-sample')}`].join(' ')
}

/** A report is at most a few hundred bytes of JSON. Anything larger is not a
 *  browser, so it is capped far below the site's general body limit. */
const MAX_REPORT_BYTES = 16 * 1024
const NO_CONTENT = new Response(null, { status: 204, headers: { 'cache-control': 'no-store' } })

export default async (req: Request, context?: Pick<Context, 'ip'>): Promise<Response> => {
  if (req.method !== 'POST') return NO_CONTENT
  // Generous, because one page load can legitimately emit several violations,
  // but bounded, because this is an unauthenticated write to the log.
  if (checkRateLimit(req, context?.ip, 60)) return NO_CONTENT

  const raw = await readBody(req, MAX_REPORT_BYTES)
  if (raw instanceof Response) return NO_CONTENT

  try {
    for (const report of violations(JSON.parse(raw)).slice(0, 10)) console.warn(line(report))
  } catch { /* A report we cannot parse is still not worth an error response. */ }

  return NO_CONTENT
}

export const config: Config = {
  path: '/api/csp-report',
  rateLimit: { windowLimit: 60, windowSize: 60, aggregateBy: ['ip', 'domain'] },
}
