// GENERATED by scripts/cut-wardrobe-stickers.mjs -- do not edit by hand.
//
// Where the CARCASS sits inside each cut-out, as fractions of the file.
//
// Not the same as the file's own bounds, and that difference is what keeps the
// wardrobe standing on the floor. Every sticker is staged: cases and boxes on
// top, shoes and a holdall on the floor in front. The traced quad is the
// CABINET, so the cabinet is what has to land on it -- the props then fall
// outside the trace on their own, which is exactly where they belong.

export interface WardrobeCutout {
  id: string;
  view: 'front' | 'angle' | 'interior';
  file: string;
  /** Pixel size of the cut-out file. */
  w: number;
  h: number;
  /** The carcass box within the file, 0..1. */
  x0: number; y0: number; x1: number; y1: number;
}

export const WARDROBE_CUTOUTS: WardrobeCutout[] = [
  {
    id: "12.0U",
    view: "interior",
    file: "12.0U-white-interior.png",
    w: 1254,
    h: 1254,
    x0: 0.63716,
    y0: 0.33333,
    x1: 0.69777,
    y1: 0.49123
  },
  {
    id: "2.9",
    view: "front",
    file: "2.9-white-front.png",
    w: 1254,
    h: 1254,
    x0: 0.18022,
    y0: 0.10925,
    x1: 0.82217,
    y1: 0.87241
  },
  {
    id: "3.0",
    view: "front",
    file: "3.0-white-front.png",
    w: 1254,
    h: 1254,
    x0: 0.07257,
    y0: 0.15152,
    x1: 0.95295,
    y1: 0.82137
  },
  {
    id: "4.0",
    view: "front",
    file: "4.0-white-front.png",
    w: 1265,
    h: 1243,
    x0: 0.0664,
    y0: 0.14401,
    x1: 0.98024,
    y1: 0.82784
  },
  {
    id: "4.9",
    view: "angle",
    file: "4.9-white-angle.png",
    w: 1254,
    h: 1254,
    x0: 0.17783,
    y0: 0.14434,
    x1: 0.83812,
    y1: 0.90351
  },
  {
    id: "5.0",
    view: "front",
    file: "5.0-white-front.png",
    w: 1307,
    h: 1203,
    x0: 0.04438,
    y0: 0.17955,
    x1: 0.95027,
    y1: 0.85786
  },
  {
    id: "6.0",
    view: "front",
    file: "6.0-white-front.png",
    w: 1254,
    h: 1254,
    x0: 0.05662,
    y0: 0.13078,
    x1: 0.96013,
    y1: 0.83732
  },
  {
    id: "7.0L",
    view: "interior",
    file: "7.0L-white-interior.png",
    w: 1269,
    h: 1240,
    x0: 0.05595,
    y0: 0.05806,
    x1: 0.95272,
    y1: 0.93468
  },
  {
    id: "8.0",
    view: "front",
    file: "8.0-white-front.png",
    w: 1178,
    h: 1234,
    x0: 0.00085,
    y0: 0.16288,
    x1: 0.94482,
    y1: 0.8436
  },
  {
    id: "9.0L",
    view: "interior",
    file: "9.0L-white-interior.png",
    w: 1448,
    h: 1086,
    x0: 0.87293,
    y0: 0.40424,
    x1: 0.90746,
    y1: 0.99908
  }
];

export const cutoutFor = (id: string): WardrobeCutout | undefined =>
  WARDROBE_CUTOUTS.find(c => c.id === id);
