// ---------------------------------------------------------------------------
// WRITES dist/robots.txt, AND DECIDES ITS CONTENTS FROM THE DEPLOY URL.
//
// THE PROBLEM IT SOLVES. There was no robots.txt at all, and the SPA catch-all
// in netlify.toml answers every unmatched path with index.html — so a crawler
// asking for /robots.txt got HTTP 200, `content-type: text/html`, and a
// webpage. A crawler that cannot parse a robots file concludes nothing is
// disallowed, so the pre-launch site on klay-website.netlify.app was fully
// open to indexing: competing with the real domain in search results, and
// reachable by anyone who might submit a real enquiry into it.
//
// WHY IT IS DERIVED RATHER THAN A FILE SOMEBODY REMEMBERS TO EDIT. A static
// public/robots.txt saying "Disallow: /" would fix today and break launch day —
// the moment the custom domain goes live it would keep Google out of the real
// site, which is worse than the problem being fixed. The alternative is a note
// on a checklist, and SPECIFICATION.md §0 is explicit about what those are
// worth: "a rule that relies on someone remembering it is not a rule, it is a
// hope."
//
// So it reads Netlify's own URL for the deploy and answers accordingly. Nobody
// has to do anything at launch; pointing the domain at the site is what flips
// it.
//
//   *.netlify.app   -> Disallow: /     a staging address, keep it out of search
//   anything else    -> Allow          the real domain, index it
//   URL unset        -> Disallow: /    a local build. Fail toward not-indexed:
//                                      being missing from Google is recoverable,
//                                      being indexed at the wrong hostname is
//                                      slow and annoying to undo.
//
// Netlify sets URL to the site's primary address at build time. Once a custom
// domain is primary, Netlify also 301s the .netlify.app host to it — so the
// staging address stops resolving separately anyway, and this becomes belt to
// that braces.
//
//   node scripts/emit-robots.mjs        (runs as part of `npm run build`)
// ---------------------------------------------------------------------------

import fs from 'node:fs';
import path from 'node:path';

const OUT = path.join('dist', 'robots.txt');

/** Netlify's own name for where this deploy will live. DEPLOY_PRIME_URL is the
 *  branch/preview address; URL is the site's primary one. Preferring URL means
 *  a preview deploy of the production branch is judged by the site's real
 *  address, which is what we want — previews are already noindexed by Netlify. */
const deployUrl = process.env.URL || process.env.DEPLOY_PRIME_URL || '';

/** True for the Netlify-assigned hostname, false for a real domain. Matches the
 *  host only: a custom domain that merely CONTAINS the string — say
 *  "netlify.app.klayinteriors.com.au" — must not be treated as staging. */
const isStagingHost = (() => {
  if (!deployUrl) return true; // no URL: local build, fail closed
  try {
    return new URL(deployUrl).hostname.endsWith('.netlify.app');
  } catch {
    return true; // unparseable: fail closed
  }
})();

const staging = `# Staging deploy — ${deployUrl || 'local build, no URL set'}
#
# GENERATED by scripts/emit-robots.mjs. Do not edit by hand, and do not commit a
# robots.txt to public/ — this file is written at build time from the deploy URL
# so that the real domain is indexable without anyone having to remember to
# change anything. See the script's header.
#
# This address is not the site's public home. Keeping it out of search stops it
# competing with the real domain and stops strangers submitting enquiries into
# a pre-launch deploy.
User-agent: *
Disallow: /
`;

// NO Sitemap: LINE, deliberately. There is no sitemap.xml — pointing at one
// that 404s is worse than omitting the directive, because the SPA catch-all
// would answer it with index.html and a crawler would try to read a webpage as
// XML. Add the line in the same commit that adds a real sitemap, not before.
const production = `# ${deployUrl}
#
# GENERATED by scripts/emit-robots.mjs from the deploy URL. Do not edit by hand.
User-agent: *
Allow: /
`;

if (!fs.existsSync('dist')) {
  console.error('emit-robots: no dist/ — run this after `vite build`.');
  process.exit(1);
}

fs.writeFileSync(OUT, isStagingHost ? staging : production);
console.log(
  `emit-robots: ${isStagingHost ? 'DISALLOW ALL' : 'allow indexing'} ` +
    `(${deployUrl || 'no URL set — treated as local'})`,
);
