// GENERATED by tools/generate-fabric-shots.mjs -- do not edit by hand.
//
// One photograph per product and fabric. Together these cover every
// configuration the shop offers, because the dimensions that do not change the
// picture -- window size, operation, hardware colour -- are not multiplied into
// the file set, and colour is applied as a dye in the browser rather than baked.
//
// ENUMERATED, NOT CONSTRUCTED, and that is the point of the file. A path built
// at runtime is invisible to every audit in the repository; see the
// specification's note on why, and what it cost the wardrobe renders to learn.
// Because each entry carries its own `file` string, `npm run check:fabric-shots`
// can assert that all of them are still on disk.
//
// A shot with a `mask` is DYED: the fabric in it has been normalised to white,
// and the card multiplies the chosen colour through the mask. One mask serves
// every fabric of a product -- they are the same window in the same room, so the
// blind occupies the same pixels in all of them.

export interface FabricShot {
  /** Catalogue item id. */
  product: string;
  /** Variant id within that product -- its 'Fabric type' or equivalent. */
  fabric: string;
  /** File name within /images/fabrics. */
  file: string;
  /** Mask file name, or null where the variant IS the material and there is
   * nothing to dye -- timber is timber-coloured. */
  mask: string | null;
}

export const FABRIC_SHOT_DIR = '/images/fabrics';

export const FABRIC_SHOTS: FabricShot[] = [
  { product: 'roller-blinds', fabric: 'blockout', file: 'roller-blinds-blockout.webp', mask: 'roller-blinds.mask.png' },
  { product: 'roller-blinds', fabric: 'dual', file: 'roller-blinds-dual.webp', mask: 'roller-blinds.mask.png' },
  { product: 'roller-blinds', fabric: 'lightfilter', file: 'roller-blinds-lightfilter.webp', mask: 'roller-blinds.mask.png' },
  { product: 'roller-blinds', fabric: 'sunscreen', file: 'roller-blinds-sunscreen.webp', mask: 'roller-blinds.mask.png' },
];

/** The shot for a configuration, or undefined where none has been photographed
 * yet -- the card falls back to the product's own hero image. */
export const fabricShot = (product: string, fabric: string | undefined): FabricShot | undefined =>
  fabric === undefined
    ? undefined
    : FABRIC_SHOTS.find(s => s.product === product && s.fabric === fabric);
